### ISSUE TITLE
Include a captain section

### ISSUE THREAD

**Issue by hsanjuan** [RichardLitt/generator-standard-readme#14]
It would be something like

## Captain

This project is currently captained by @userxyzabc. For information about current state and goals, see the [captain log](linktocaptain.log).

**Comment by RichardLitt** [comment]
I think this should be int he Maintainers section. I have been doing this:

```
## Maintainers

Captain: @hsanjuan. 
```

Listing the information about what a captain is is something we can do. But I don't think that every README should have a Captain, so I don't think this is a good section. It also privileges Captains over other maintainers. The [linter I've been using for IPFS repos](https://github.com/RichardLitt/standard-readme-linter-regex) checks for a captain the maintainer section; that should solve your need here.

**Comment by hsanjuan** [comment]
Ah, sorry, i didnt realize there was a maintainers section already!

**Comment by RichardLitt** [comment]
It should be there, actually. Opened a PR.

**Comment by RichardLitt** [comment]
Fixed. Updated.
