### ISSUE TITLE
Generator isn't inserting the user-specified license type in the README output

### ISSUE THREAD

**Issue by jeff-matthews** [RichardLitt/generator-standard-readme#16]
Great project! It's been really useful to me, but I'm encountering a problem when entering a license other than MIT. 

When I enter something other than MIT, like ISC, it's not showing up in the README output. It only shows the copyright symbol and the text input I specified for the "licensee".

 © licensee

**Comment by RichardLitt** [comment]
Thanks! Good point. I fixed this.

**Comment by jeff-matthews** [comment]
Thanks!
