### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by noffle** [RichardLitt/generator-standard-readme#2]
some notes from me trying it:

1. It might be worth mentioning that you'll need to run `npm install -g yo` as well -- that step wasn't immediately obvious to me. (might it be easier on end-users if it just made a cli called `standard-readme`?)
2. I didn't expect this to write to `readme.md` for me, but it's cool that yo will ask to confirm and show diffs, etc.
3. I get a ~5 second delay between running the command and seeing the first dialog. Probably not worth optimizing at this point, but it seems like a strangely long delay for such a program. Maybe inherited from yo?
4. Nitpick: I'd like to see `Y` as a default for some of these :wink: -- possibly Background but almost certainly API.
5. It'd be nice if License holder defaulted to maybe `git config user.name` as a decent predicate. Or maybe something more clever like [fullname](https://github.com/sindresorhus/fullname).

I like it! The interactive menus are attractive and allay any of my fears about forgetting about a field. Having the nice merge conflict options is nice to have as well. I also dig the paren-enclosed suggested defaults for some of the fields (like name).

**Comment by noffle** [comment]
Oh, one more: as per the spec the resulting file ought to be README.md, not readme.md ("Be called README.md (with capitalization).")

**Comment by RichardLitt** [comment]
1. Updated to add `yo` to the global install. 
2. Yep, that's how Yeoman works. Added note to usage.
3. That's normal, it's a yeoman thing. I don't think that this is a problem; this is a rare event.
4. I don't think that Background is necessary - for most libraries, it can be covered in the long description. I also don't think that API is _always_ necessary - it is something that pertains to a lot of libraries, but certainly not everything. For instance, it doesn't pertain to this one, or to go-ipfs. Some frameworks won't need it, and I'm really hesitant to make it a must-have. I know where you're coming from, but this needs to work for other languages and tools - like CLI tools, which may not have the same needs and requirements - as publicly exported functions. Maybe [open an issue in standard-readme](//github.com/RichardLitt/standard-readme/issues/new)?
5. Yeah. That would be a cool thing to do. This was a fast job - there's some other stuff I want, too, like extra sections. Opened #3. 
6. Hmm. You know, I'm actually not sure that README vs. readme is important. Opened https://github.com/RichardLitt/standard-readme/issues/11

Glad you like it! Yeoman is pretty badass.

**Comment by noffle** [comment]
4. Maybe I miscommunicated -- I meant have these fields default to `Yes`, not making them must-haves / required.

**Comment by RichardLitt** [comment]
Ah! That's something to consider. Yeah, I think I can go for that.

**Comment by RichardLitt** [comment]
Twitter appears to agree with you so far.

**Comment by noffle** [comment]
I feel much less opinionated about these things now than I did once upon a time. Closing!
