### ISSUE TITLE
The readme filename in this repository isn't spec compliant

### ISSUE THREAD

**Issue by per1234** [RichardLitt/generator-standard-readme#24]
https://github.com/RichardLitt/standard-readme/blob/master/spec.md states:

>A compliant README must satisfy all the requirements listed below.

...

>Be called README.md (**with capitalization**).

However, the readme filename in this repository is readme.md: https://github.com/RichardLitt/generator-standard-readme/blob/master/readme.md

**Comment by RichardLitt** [comment]
Thank you, @per1234. I'm working on a better linter to catch stuff like this, automatically.

Would you be interested in filing a PR? Otherwise, I can change this.
