### ISSUE TITLE
standard-readme should be listed as a dependency

### ISSUE THREAD

**Issue by kylemh** [RichardLitt/generator-standard-readme#30]
Following the instructions for installation and usage, word-for-word will not work. The user must have https://www.npmjs.com/package/standard-readme installed globally, first.

**Comment by RichardLitt** [comment]
You're right - I changed how [standard-readme](https://github.com/RichardLitt/standard-readme) works and forgot to update this package. I've removed the old instructions and gone back to just using `yo`, which I think is cleaner.
