### ISSUE TITLE
Description appears in the same line as the badges

### ISSUE THREAD

**Issue by hsanjuan** [RichardLitt/generator-standard-readme#9]
I think there is a line break missing in the template

**Comment by RichardLitt** [comment]
@hsanjuan I am unable to reproduce this. I fixed the tests so that they work; can you create a test case for where this happens?

**Comment by hsanjuan** [comment]
I think this is fixed and existing test case should cover it

**Comment by RichardLitt** [comment]
Thanks @hsanjuan!
